import { test, expect } from '@playwright/test';

test('Globe, playback, scrubbing, sources, camera and mobile controls', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/');
  await expect(page.getByRole('button',{name:'Play timeline',exact:true})).toBeEnabled();
  await expect(page.locator('.territory-legend')).toContainText('Newfoundland');
  await expect(page.locator('canvas')).toBeVisible();
  await page.waitForTimeout(1100); // Initial camera easing must settle before measuring it.
  const globe=page.locator('.globe-canvas');
  const before=await globe.getAttribute('data-camera-lng');
  await page.mouse.move(780,380); await page.mouse.down(); await page.mouse.move(930,420,{steps:12}); await page.mouse.up();
  await expect.poll(()=>globe.getAttribute('data-camera-lng')).not.toEqual(before);
  await page.waitForTimeout(500);
  const zoomBefore=Number(await globe.getAttribute('data-camera-altitude'));
  await page.mouse.wheel(0,-200); await page.waitForTimeout(400);
  expect(Number(await globe.getAttribute('data-camera-altitude'))).toBeLessThan(zoomBefore);
  await page.getByRole('button',{name:'Reset North America view'}).click(); await page.waitForTimeout(1100);
  await expect.poll(async()=>Math.abs(Number(await globe.getAttribute('data-camera-lng'))+103)).toBeLessThan(1);
  const cameraBefore=await globe.getAttribute('data-camera-lng');
  await page.getByRole('combobox',{name:'Playback speed'}).selectOption('12');
  await page.getByRole('button',{name:'Play timeline',exact:true}).click();
  await expect(page.getByRole('button',{name:'Pause timeline',exact:true})).toBeVisible();
  await expect.poll(()=>page.locator('.app').getAttribute('data-year')).not.toEqual('1880');
  expect(Number(await globe.getAttribute('data-camera-lng'))).toBeCloseTo(Number(cameraBefore),2);
  const timeline=await page.locator('.timeline').boundingBox();
  await page.mouse.move(timeline!.x+timeline!.width/2,timeline!.y+15); await page.mouse.wheel(0,100);
  await expect(page.getByRole('button',{name:'Play timeline',exact:true})).toBeVisible();
  const pausedYear=await page.locator('.app').getAttribute('data-year');await page.waitForTimeout(250);
  expect(await page.locator('.app').getAttribute('data-year')).toEqual(pausedYear);
  const jump=page.getByRole('spinbutton',{name:'Jump to year'});
  await jump.fill('1776');await jump.press('Enter');
  await expect(page.locator('.app')).toHaveAttribute('data-year','1776');
  await expect(page.locator('.coverage-status')).toContainText('No snapshot');
  await expect(page.locator('.territory-legend')).toHaveCount(0);
  await page.getByRole('button',{name:'Next snapshot',exact:true}).click();
  await expect(page.locator('.app')).toHaveAttribute('data-year','1880');
  await page.getByRole('button',{name:'View 1938 snapshot',exact:true}).click();
  await expect(page.locator('.app')).toHaveAttribute('data-year','1938');
  await expect(page.locator('.territory-legend')).toContainText('United States');
  await expect(page.locator('.territory-legend')).not.toContainText('Hawaiian Kingdom');
  await page.getByRole('button',{name:'Sources & coverage',exact:true}).click();
  await expect(page.locator('dialog')).toHaveJSProperty('open',true);
  await expect(page.locator('dialog')).toContainText('Newfoundland’s entry into Confederation');
  await page.keyboard.press('Escape'); await expect(page.locator('dialog')).toHaveJSProperty('open',false);
  await page.getByRole('button',{name:'Open layer controls'}).click();
  await page.getByRole('switch',{name:'Territorial borders'}).click();
  await expect(page.getByRole('switch',{name:'Territorial borders'})).toHaveAttribute('aria-checked','false');
  await page.getByRole('button',{name:'Close panel'}).click();
  await jump.fill('1880'); await jump.press('Enter');
  await expect(page.locator('.territory-legend')).toContainText('Newfoundland');
  await page.screenshot({path:'artifacts/desktop.png'});
  await page.setViewportSize({width:390,height:844});await page.waitForTimeout(1100);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await expect(page.getByRole('button',{name:'Play timeline',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Sources & coverage',exact:true}).click();
  await expect(page.locator('dialog')).toHaveJSProperty('open',true);
  await page.getByRole('button',{name:'Close panel'}).click();
  await page.screenshot({path:'artifacts/mobile.png'});
  expect(errors).toEqual([]);
});
